name: Scrape Download Count

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # This will run the action daily at midnight

jobs:
  scrape-download-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.JCANNON_GIT_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Run the scraper
        run: python scrape.py
        env:
          GH_TOKEN: ${{ secrets.JCANNON_GIT_PAT }}

      - name: Commit and push data file
        run: |
          git config --global user.name 'Joshua Cannon'
          git config --global user.email 'noreply@github.com'
          git add data/*
          git commit -m "Add today's data"
          git push origin main
